SOURCE_DIR = c_sources

SOURCES = $(wildcard $(SOURCE_DIR)/*.c)

#output:
#	flex -o c_sources/scanner.c flex_sources/scanner.l 
#	gcc $(SOURCES) -o scanner
output:
	gcc c_sources/preprocessor.c -o preprocessor
